eapp/urls.py
from django.urls import path
from . import views

app_name='eapp'

urlpatterns=[
    path('',views.index,name='index'),
    path('(?P<event_id>[0-9]+)/',views.details,name='details'),
    path('add_event',views.add_Event,name='add_event'),
    path('(?P<event_id>[0-9]+)/comment/',views.comment,name='comment'),
    path('(?P<event_id>[0-9]+/login/edit/',views.login_edit,name='login_edit'),
    path('(?P<event_id>[0-9]+/delete',views.delete,name='delete'),
]

event/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('eapp.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

eapp/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    event_creator = models.CharField(max_length=40)
    event_password = models.CharField(max_length=40)
    name=models.CharField(max_length=40)
    venue=models.CharField(max_length=40)
    date=models.DateField()
    time=models.TimeField()
    charges=models.CharField(max_length=40)
    contact=models.IntegerField()
    banner=models.ImageField()
    description=models.TextField()

    def __str__(self):
        return self.name

class Comment(models.Model):
    event_name=models.ForeignKey(Event, on_delete=models.CASCADE)
    user_name=models.CharField(max_length=40)
    comment = models.TextField(max_length=100000000000)

    def __str__(self):
        return self.user_name

eapp/forms.py
from django import forms
from .models import Event,Comment
from django.contrib.auth.models import User


class EventForm(forms.ModelForm):
    class Meta:
        model=Event
        fields=['event_creator','event_password','name','venue','date','time','charges','contact','banner','description']

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['user_name','comment']

class LoginForm(forms.ModelForm):
    event_password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=Event
        fields=['event_creator','event_password']

eapp/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Event,Comment
from .forms import EventForm,CommentForm,LoginForm

# Create your views here.

def index(request):
    events=Event.objects.all
    context={
        'events':events
    }
    return render(request,'eapp/index.html',context)

def details(request, event_id):
    event=get_object_or_404(Event, pk=event_id)
    return render(request,'eapp/details.html',{'event':event})


def add_Event(request):
    formEvent=EventForm(request.POST or None, request.FILES or None)
    if formEvent.is_valid():
        event=formEvent.save(commit=False)
        event.save()
        return render(request,'eapp/details.html',{'event':event})
    return render(request,'eapp/event_adding.html',{'formEvent':formEvent})

def comment(request,event_id):
    event=get_object_or_404(Event, pk=event_id)
    formComment=CommentForm(request.POST or None, request.FILES or None)
    if formComment.is_valid():
        user_comment=formComment.save(commit=False)
        user_comment.event_name=event
        user_comment.save()
        return render(request,'eapp/details.html',{'event':event})
    return render(request,'eapp/commenting.html',{'formComment':formComment})

def login_edit(request,event_id):
    event_name=get_object_or_404(Event, pk=event_id)

    formEvent=EventForm(request.POST or None, request.FILES or None, instance=event_name)
    formLogin=LoginForm(request.POST or None)
    if formLogin.is_valid():
        name=formLogin.cleaned_data[
            'event_creator'
        ]
        password=formLogin.cleaned_data[
            'event_password'
        ]
        if name==event_name.event_creator and password==event_name.event_password:
            if formEvent.is_valid():
                update_details=formEvent.save(commit=False)
                update_details.save()
                return redirect('eapp:index')
            return render(request,'eapp/event_adding.html',{'formEvent':formEvent})

        else:
            message = {'message': ' Invalid Credentials ', 'formLogin': formLogin}
            return render(request, 'eapp/login.html', message)

    return render(request,'eapp/login.html',{'formLogin':formLogin})


def delete(request,event_id):
    event_name=get_object_or_404(Event, pk=event_id)
    formLogin=LoginForm(request.POST or None)
    if formLogin.is_valid():
        name=formLogin.cleaned_data[
            'event_creator'
        ]
        password=formLogin.cleaned_data[
            'event_password'
        ]
        if name==event_name.event_creator and password==event_name.event_password:
            event_name.delete()
            return redirect('eapp:index')
    return render(request,'eapp/login.html',{'formLogin':formLogin})

eapp/templates/eapp/base.html
<title>{% block title %} {% endblock %}</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Lora' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Baloo Bhai' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=QuickSand' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Prompt' rel='stylesheet'>

{% load static %}
<link rel="stylesheet" href="{% static 'eapp/css/style.css' %}" type="text/css">

<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <div class="container-fluid">
    <div class="navbar-header">
        <div class="row">
            <div class="col-sm-2">
                <a class="navbar-brand" href="{% url 'eapp:index' %}" style="font-family: 'Acme', cursive;"> WILDFIRE </a>
            </div>
            <div class="col-sm-6">
                <form class="navbar-brand form-inline my-2 my-lg-0">
                    <div class="row">
                        <div class="col-sm-9">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.GET.q }}">
                        </div>
                        <div class="col-sm-3">
                            <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-sm-4">
                <a class="navbar-brand" href="{% url 'eapp:add_event' %}" style="font-family: 'Acme', cursive;"><i class="fas fa-calendar"></i> ADD EVENT </a>
            </div>
        </div>
    </div>
  </div>
</nav>
<div class="container">
    {% block content %}

    {% endblock %}
</div>

eapp/templates/eapp/commenting.html
{% extends 'eapp/base.html' %}
{% block title %} WildFire: {{event.name}} Comments {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
        <div class="panel panel-info panel-body" style="margin: 50px; border-color: LightBlue">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{formComment|crispy}}
                <div class="form-group">
                    <button class="btn btn-info" style="width:425px;">SUBMIT</button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-sm-3"></div>
</div>

{% endblock %}

eapp/templates/eapp/details.html
{% extends 'eapp/base.html' %}
{% block title %} WildFire: {{event.name}} {% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-3">
            <div class="panel panel-info" >
                <img src="{{event.banner.url}}" class="img img-thumbnail img-responsive">
                <h4 style="font-family:Pacifico; margin:5px;">{{event.name}}</h4>
                <h4 style="font-family:Lora; margin:5px;">{{event.date}} {{event.time}}</h4>
            </div>
        </div>
        <div class="col-sm-9">
            <div class="panel panel-info" style="margin: 5px;">
                <div class="panel panel-header" style="margin: 10px;">
                    <h3 style="font-family:Baloo Bhai; text-align:center; margin:10px;">{{event.name}}</h3>
                    <h5 style="font-family: Prompt; margin:10px;">
                        {{event.description}}
                    </h5>
                </div>
                <div class="panel panel-body" style="margin: 10px;">
                    <h4 style="font-family:Pacifico; float:right; margin-left:275px;">Contact:<p style="font-family: Lora">{{event.contact}}</p></h4>
                    <h4 style="font-family:Pacifico; float:right">Charges:<p style="font-family: Lora">{{event.charges}}</p></h4>
                    <h4 style="font-family:Pacifico;">Venue:<p style="font-family: Lora">{{event.venue}}</p></h4>
                </div>
                <div class="panel panel-footer panel-info" style="margin:10px;">
                    <h4 style="font-family:Baloo Bhai">Comments</h4>
                        {% for c in event.comment_set.all %}
                            <p><h5>"{{c.comment}}" <i style="font-family:Oswald">Comment by:    <a href=""> <u>{{c.user_name}} </u></a></i></h5></p>
                        {% endfor %}
                </div>
                <div class="panel panel-footer panel-info" style="margin:10px; margin-left:560px;">
                    <a href="{% url 'eapp:comment' event.id %}">
                        <i class="fas fa-comments"> Comment</i>
                    </a>
                    <a href="{% url 'eapp:login_edit' event.id %}" style="margin-right: 20px;">
                        <i class="fas fa-edit" style="margin-left:20px;"> Edit</i>
                    </a>
                    <a href="{% url 'eapp:delete' event.id %}" style="" onclick="return confirm('Are you sure you want to delete this event?')">
                        <i class="fas fa-trash"> Delete</i>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

eapp/templates/eapp/event_adding.html
{% extends 'eapp/base.html' %}
{% block title %}WildFire: Add Event{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
        <div class="panel panel-body" style="margin: 50px; border-color: LightBlue">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ formEvent|crispy }}
                <div class="form-group">
                    <button class="btn btn-info" style="width:410px;">CREATE</button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-sm-3"></div>
</div>
{% endblock %}

eapp/templates/eapp/index.html
{% extends 'eapp/base.html' %}
{% block title %} WildFire: Home {% endblock %}
{% block content %}
   <div class="row">
       {% for event in events %}
       <div class="col-sm-4">
           <div class="panel panel-default" style="background-color: lightblue; margin:10px;">
               <div class="row">
                   <div class="col-sm-5">
                       <a href="{% url 'eapp:details' event.id %}">
                           <img src="{{event.banner.url}}" style="height:150px; width: 250px; margin:10px" class="img img-thumbnail">
                       </a>
                   </div>
                   <div class="col-sm-7">
                       <h4 style="font-family: Pacifico">{{event.name}}</h4>
                       <h4 style="font-family: Lora">{{event.date}} {{event.time}}</h4>
                   </div>
               </div>
           </div>
       </div>
       {% endfor %}
   </div>
{% endblock %}

eapp/templates/eapp/login.html
{% extends 'eapp/base.html' %}
{% block title %} WildFire: {{event.name}} Comments {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
        <div class="panel panel-info panel-body" style="margin: 50px; border-color: LightBlue">
            {% if message %}
                <div class="alert alert-danger">
                    <h4>{{message}}</h4>
                </div>
            {% endif %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{formLogin|crispy}}
                <div class="form-group">
                    <button class="btn btn-info" style="width:425px;">LOGIN</button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-sm-3"></div>
</div>

{% endblock %}